# Generated by Django 5.0.6 on 2024-06-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MalwareDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('malware_name', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
